spring:
  data:
    mongodb:
      uri: 
      database: journaldb
      auto-index-creation: true

server:
  port: 8080
  servlet:
    context-path: /

# logging:
#  level:
#    root: ERROR

#logging:
#  level:
#    com:
#      springboot: ERROR
